# Generated by Django 4.0 on 2023-02-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0020_alter_article_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
    ]
