# Generated by Django 4.0 on 2023-03-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0021_remove_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preamble',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
