# Generated by Django 4.0 on 2023-03-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0025_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sitle',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=20, null=True, unique=True),
        ),
    ]
