# Generated by Django 4.0 on 2023-03-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0026_course_sitle_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
