# Generated by Django 4.0 on 2023-03-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0028_article_date_article_update_course_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='update',
            field=models.CharField(choices=[('t', 'true'), ('f', 'false')], max_length=1, null=True),
        ),
    ]
