# Generated by Django 4.0 on 2023-03-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0029_alter_article_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='update',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
