# Generated by Django 4.0 on 2023-03-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0030_alter_article_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
