# Generated by Django 4.0 on 2023-03-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0033_article_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Video',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
