# Generated by Django 4.0 on 2023-03-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0034_alter_course_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Topic',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
